### PR TITLE
Removed extra menus that appeared (fixes #50)

### LINKED ISSUE #50: fix Research dropdown on the data.html page
Once you click on Research in the navigation bar, a placeholder menu pops up and it doesn't link to the nzertf Research website.

### PR DESCRIPTION
**Pull request by radhikabhatt26**

### CODE REVIEW

**Comment by maabrown** [comment]
Hey @radhikabhatt26  - Why did you delete DOCTYPE from the index.html page? I always thought it was best practice to always have the DOCTYPE tag on your html.

**Comment by radhikabhatt26** [comment]
@maabrown SO - I actually added the DOCTYPE tag because it wasn't there, thinking it was a best practice to have it. When I added it, the background image wouldn't show - the whole page was completely white, so you couldn't read the text either. 

I didn't know why that was happening so I reverted it back to it's original state, with no doctype tag.

**Comment by maabrown** [comment]
@radhikabhatt26  I'm gonna fool around with your code for a little bit just to see why that's happening because data.html has the DOCTYPE tag and still works...

**Comment by maabrown** [comment]
@radhikabhatt26 So I think it is best that you put <!DOCTYPE html> so that it prevents quirks and rendering problems in browsers (reference: http://stackoverflow.com/questions/6076432/why-do-i-need-a-doctype-what-does-it-do)

If you can add it back and add html,body {width: 100%, height: 100% } the index.html page should work (it did on my computer). I got my solution from: http://stackoverflow.com/questions/14172174/doctype-declaration-removes-my-background-image

If you could make those changes and re-submit that would be awesome. Let me know if you have any questions!

**Comment by maabrown** [comment]
@radhikabhatt26 Also - We could delete the unneeded D3 scripts that are in the index.html file (I'm deleting them in my data.html PR)

**Pull request merged**
